### ISSUE TITLE
Implement all `Some` Functions

### ISSUE THREAD

**Issue by ryanguill** [iwburns/nullshield#17]
Still to be implemented:

- [x] `mapOr`
- [x] `mapOrElse`

**Comment by iwburns** [comment]
Just fyi, those were actually removed for now for simplicity's sake (fully expecting to add them in later) because you can achieve the same thing with `or` and `orElse`.

Not saying this issue is in error or anything like that, just letting you know why they aren't there.

**Comment by ryanguill** [comment]
I only mentioned it because theyre in `none` right now, but throwing errors for `Method Not Implemented`
