### ISSUE TITLE
Impl all None functions

### ISSUE THREAD

**Issue by iwburns** [iwburns/nullshield#2]

**Comment by brycehipp** [comment]
I'll go head and take this on. will likely work through it tomorrow night.

**Comment by iwburns** [comment]
Btw, I just got the OptT docs and doc examples finished, so you should be able to use that as a reference.

Feel free to reach out if you think something doesn't make sense though.

**Comment by brycehipp** [comment]
awesome! that will definitely help a lot

**Comment by ryanguill** [comment]
Still to be implemented:

- [ ] `mapOr`
- [ ] `mapOrElse`
