### ISSUE TITLE
Consider Removing `*OrElse` method variants

### ISSUE THREAD

**Issue by iwburns** [iwburns/nullshield#39]
### Proposal
Remove `*OrElse` methods in favor of more flexible `*Or` methods.

I'm wondering if it makes more sense to get rid of things like `unwrapOrElse()` in favor of allowing functions to be passed into `unwrapOr()`.

To clarify, here's the current API (for just this example):

`unwrapOr(other: T): T`
`unwrapOrElse(func: () => T): T`

and I'm proposing we switch to:

`unwrapOr(other: T | (() => T)): T`

In other words, allow either a `T`-type value to be passed in _or_ a function that returns a `T`-type value.  I think it makes more sense this way from a TypeScript / JavaScript perspective (but maybe that's not true?).  It also has the added benefit of reducing the size of our API which I'm always happy with (assuming it makes sense).

### Difficulty
It should be easy enough to do implementation-wise, don't see any road-blocks right away.

### Drawbacks
I don't see anything major other than this being a breaking change (good thing we're pre-1.0.0 right now).  If we decide to do this, I'd like to get it out before 1.0.0 of course, so that puts this on the more-urgent-ish side of things.

### Misc.
There are several functions like this in both OptionT and ResultT:

OptionT:
1. `unwrapOr` / `unwrapOrElse`
2. `mapOr` / `mapOrElse`
3. `or` / `orElse`

ResultT:
1. `unwrapOr` / `unwrapOrElse`
2. `unwrapErrOr` / `unwrapErrOrElse` (technically these don't exist yet, but I can see a vague need for them in certain cases, so maybe they should be added?)

What do you guys think?  Does this make sense to do?

**Comment by ryanguill** [comment]
I thought about something similar when doing my cfml implementation recently.  Stream of consciousness incoming. 

If you take this even further you could make it simply `unwrap(other?: T | (() => T)): T` - an optional argument to unwrap that is the default for a `None`.  I could argue both ways whether this is too far or not.

One potential breaking change of this would be if you are using your Option to contain a function - you could today be doing `unwrapOr(fn)` meaning you want a different function to be _returned_ not used in the case of a `None`.

I think in general, "overloaded" methods tend to be easier to write than read - I think there is an argument to be made that the "or" and "orElse" arent very clear (I know these came from rust, but for people who aren't as familiar with the concepts of Option/Result in the first place) - but at least they are and indication that this is a different method with a different signature and semantics.

That being said, lots of JS do use overloaded methods.

For Result, the ok vs err does start to make things a little crazy to figure out which method you really want - I noticed myself that we had an `unwrapOr` but not an `unwrapErrOr`, but geez, `unwrapErrOrElse` seems more like a threat than an operation ;)

I kinda came down with it at the time that if you really want to be doing some of these things, its straightforward enough to use `match`, which would allow you to do whatever you need to.  

So, trying to some sort of conclusion, I think my current position is that we should reduce the api footprint as much as possible for 1.0 and let it see some use before we add in methods that we see had actual use cases.  I think those use cases will a) tell us what is actually useful and b) maybe inform a better naming for the api in general. But I think I could be convinced of other outcomes as well.

**Comment by iwburns** [comment]
>If you take this even further ... could argue both ways whether this is too far or not.

Honestly I didn't even think of doing that, but I think I agree that it's bordering on going too far down this path.

>One potential breaking change of this would be if you are using your Option to contain a function...

Wow... yep, that's a pretty big deal.  Really glad you brought that up.  I think that kindof shoots this down entirely tbh...  Maybe not, idk, but I definitely want to support OptionT&lt;Function&gt;, etc.

Another name that might make more sense in the JS/TS world is `unwrapOr` + `unwrapOrCall`. `call` has a meaning already, but I don't think that's a bad thing in this case necessarily (could be convinced otherwise).

>I think in general, "overloaded" methods ...

Totally see what you're saying here, and I think I agree in general, but as you say:

>...lots of JS do use overloaded methods.

which is why I was thinking this might be an appropriate step to take in this case.  However, the OptionT&lt;Function&gt; issue is still a problem I think.

>For Result, the ok vs err does start to make things a little crazy...

lol, exactly!  I initially built all of them out and then confused myself and removed them.  I then looked at the Rust docs and concluded that since they didn't support all of the weird ones I wouldn't try to either (at least for now).

>...it's straightforward enough to use `match`...

Yeah, I mostly agree, but I think it's annoying to force the user to `match` in some cases.  However, maybe that's not much of an issue in practice.  The only thing I can think of is a `map` chain (or similar) with a `mapOr`/`mapOrElse` in the middle somewhere.  It'd be annoying to have to `match` like this I'd think:
```
//this is more verbose, (but maybe clearer, depending on background)
.map(a => a.getB())
.match({ some: b => b.getC(), none: () => { return new C(); })
.map(c => c.getD())

//but this makes more sense like this to me
.map(a => a.getB())
.mapOr((new C()), b => b.getC()) 
.map(c => b.getD())
```

>I think my current position is that we should reduce the api footprint...

I'm down with that.  I'd rather have a simple, clean API than a kitchen sink.  However, I'm not so sure I can identify the things that are useful or not.  Do you have any ideas of where to start here?  Any methods that seem not-so-useful right now?

**Comment by ryanguill** [comment]
I dont like the word `call` for this purpose.

I think if you want to do `unwrapOr(other: T | (() => T)): T` and leave it at that for now, lets do that - if you want your value to be a function you can either wrap it in an anonymous function or an object or array

`unwrapOr(() => myFnIReallyWantToReturn)` / `unwrapOr([myFnIReallyWantToReturn])` - the latter youd probably expect the possible some to wrapped the same way - then its just a matter of destructuring it.

But in general, `match`, while its not the perfect answer for some use cases, should allow you to do what you need to do - so what I mean by reduce the api footprint is to leave out any function that we arent dead sure of the api or usefulness, and then let our painpoints of using it inform the api.  We can always add api, but we cant ever take it away.

**Comment by iwburns** [comment]
> We can always add api, but we cant ever take it away.

Totally get what you're saying here.  Further down below I'll list all of the functions and give my short opinion on them.  This may not be the best way to do this, but it's all I can think of right now.

I'm afraid if we went with `unwrapOr(other: T | (() => T)): T` then we'd almost be neglecting functions as first class objects.  I'd also hate to have to write the docs bit about "...this 'quirk' of the library..." unless we absolutely have to.  In addition `unwrapOrElse` actually does have a distinct use case.

If you want to fall back to something that you don't have yet (result of network call, file i/o, expensive synchronous operation, etc.) then you'd want to use `unwrapOrElse` because the function you pass isn't going to be called unless it's needed. (The current) `unwrapOr` is different in that whatever you're passing in is a value you already have.

With that in mind I now have two issues with merging those two functions: (1) I dislike that you'd have to treat functions differently if you have `Option<Function>`s, and (2) those two functions have distinct use cases (that I had forgotten about originally) that when merged may muddy the water a bit on how the function behaves.  I don't have super strong feelings about point (2), but I'm more upset about point (1).

-----
Here are my thoughts on our current API.  Please let me know what you guys think of this and if you have any thoughts to add please feel free to do so.  These are all just my opinions.

format is:  
`funcDefinition` {disposition=remove|keep} explanation

### OptionT
* `static of<T>(value?: T): OptionT<T>` {keep} I think this one is useful in enough cases that we keep it.
* `static some<T>(value: T): OptionT<T>` {keep} must-have, needed for creating `OptionT`s
* `static none<T>(value?: T): OptionT<T>` {keep} same as `some()`
* `isSome(): boolean;` {keep} most of the time you don't need to use this, but it's good for quick prototyping
* `isNone(): boolean;` {keep} same as `isSome()`
* `toString(): string;` {keep} I think this is useful enough for debugging that we shouldn't remove it
* `expect(message: string): T;` {keep} must-have, for cases when there is no valid fall-back value that you can use and you just want to throw an error because you can't continue forward in the program.
* `unwrap(): T;` {keep} normally, using this is a no-no, but it's nice for quick prototyping
* `unwrapOr(other: T): T;` {keep} must-have, bread and butter of getting a value out of an `OptionT`
* `unwrapOrElse(func: () => T): T;` {keep} for reasons stated above, this is useful when the fall-back value isn't something you already have and may be expensive to compute.
* `map<U>(func: (val: T) => U): OptionT<U>;` {keep} must-have, useful for transforming one `OptionT` into another `OptionT`
* `mapOr<U>(other: U, func: (val: T) => U): U;` {remove} just a convenience function for `.map(...).unwrapOr(...)`
* `mapOrElse<U>(other: () => U, func: (val: T) => U): U;` {remove} just a convenience function for `.map(...).unwrapOrElse(...)`
* `and<U>(other: OptionT<U>): OptionT<U>;` {keep} useful for chained confirmation that items are `Some` values
* `flatMap<U>(func: (val: T) => OptionT<U>): OptionT<U>;` {keep} on the fence here, but flatMap is such a staple that I don't want to remove it.  It's really just slightly different semantics on `map`.
* `or(other: OptionT<any>): OptionT<any>;` {keep} useful for chaining defaults (when followed by an `unwrap`/`expect` ).  I'm on the fence on this one b/c I've never had to use it, but I could see it being useful.
* `orElse(func: () => OptionT<any>): OptionT<any>;` {keep} same as `or()` except that it lazily evaluates `func` which may be useful if that operation is expensive.  I've never had to use it, but it seems like it'd be useful.
* `match<U, V>(options: OptMatch<T, U, V>): U | V;` {keep} must-have, shotgun approach to dealing with `OptionT`s
* `clone(): OptionT<T>;` {remove} not sure if this is useful or not
* `filter(condition: (val: T) => boolean): OptionT<T>;` {keep} can see this being very useful
* `forEach(func: (val: any) => void): void;` {keep} although side-effect-causing functions should be discouraged, this would be useful in certain situations.
* `equals(other: OptionT<any>): boolean;` {remove} not sure if this is useful or not
* `hasValue(val: any): boolean;` {remove} not sure if this is useful or not
* `contains(condition: (val: T) => boolean): boolean;` {remove} not sure if this is useful or not

**Comment by ryanguill** [comment]
I would probably disagree with you on a few of your rationales, but I dont think I disagree with any of your conclusions.

**Comment by iwburns** [comment]
Understood.  I'm not at my PC right now, but I'd like to do the same for `ResultT` here soon.

**Comment by iwburns** [comment]
Same as above for `ResultT`:

* `static ok<T>(val: T): ResultT<T, any>` {**keep**} must-have, required for making `ResultT`s
* `static err<E>(error: E): ResultT<any, E>` {**keep**} must-have same as `ok()`
* `isOk(): boolean;` {**keep**} same as `isSome()` and `isNone()`
* `isErr(): boolean;` {**keep**} same as `isSome()` and `isNone()`
* `toString(): string;` {**keep**} same as `OptionT.toString()`
* `getOk(): OptionT<T>;` {**keep**} useful when you don't care about the specific Error that you might have, just whether or not you got a "good" value back from something.
* `getErr(): OptionT<E>;` {**keep**} on the fence here, this seems less useful than `getOk`, but I can maybe see where you might want to only care about the error that a function returns and not the "good" value.  Could almost argue though that you should just be returning an `OptionT<MyError>` at that point though (which is what this would give you).
* `expect(message: string): T;` {**keep**} same as `OptionT.expect()`
* `expectErr(message: string): E;` {**remove**} on the fence here, seems not so useful, but I could be wrong, maybe it is useful. Also, symmetry is nice, but I don't want to chase symmetry just for symmetry's sake.
* `unwrap(): T;` {**keep**} same as `OptionT.unwrap()`
* `unwrapErr(): E;` {**keep**} useful enough that we keep it, although I think this one will be not so commonly used.
* `unwrapOr(other: T): T;` {**keep**} same as `OptionT.unwrapOr()`
* `unwrapOrElse(func: (err: E) => T): T;` {**keep**} same as `OptionT.unwrapOrElse()`
* `map<U>(func: (val: T) => U): ResultT<U, E>;` {**keep**} pretty useful for transforming values
* `mapErr<F>(func: (val: E) => F): ResultT<T, F>;` {**keep**} seems useful enough although likely less commonly used.
* `and<U>(other: ResultT<U, E>): ResultT<U, E>;` {**doesn't exist**} seems like we should add this, maybe? maybe not?
* `flatMap<U>(func: (ok: T) => ResultT<U, E>): ResultT<U, E>;` {**keep**} could be removed if needed, but again, it's such a staple that I feel bad removing it
* `or<F>(other: ResultT<T, F>): ResultT<T, F>;` {**doesn't exist**} seems like we should add this, maybe? maybe not?
* `orElse<F>(func: (err: E) => ResultT<T, F>): ResultT<T, F>;` {**keep**} seems useful enough to keep
* `match<U, F>(options: ResultMatch<T, E, U, F>): U | F;` {**keep**} must have, shotgun approach to dealing with `ResultT`s
* `clone(): ResultT<T, E>;` {**remove**} not sure this is useful
* `equals(other: ResultT<T, E>): boolean;` {**remove**} not sure this is useful
* `hasValue(val: T | E): boolean;` {**remove**} not sure this is useful
* `contains(func: (val: T | E) => boolean): boolean;` {**remove**} not sure this is useful

**Comment by iwburns** [comment]
I'm going to go ahead and move forward with this and update the existing "cleanup" branch I have with the above removals.

We can take a look when that PR is updated and see if anything doesn't look good, but please feel free to leave comments here as well if you guys think of anything.

**Comment by iwburns** [comment]
Alright, this stuff is all complete and a new version (0.7.1) has been published.
