### ISSUE TITLE
Consider name change for `OptionT<T>`

### ISSUE THREAD

**Issue by iwburns** [iwburns/nullshield#49]
I'd like to consider changing `OptionT<T>` to something less "bad" - for the lack of a better term - before we go 1.0.  This is partly because it forces `Result<T, E>` to be `ResultT<T, E>` for consistency purposes, but also because I just don't like `OptionT<T>` at all.

In addition, if we were to move forward with #40 (which I'd really like to do in some form or fashion, but maybe not until after 1.0). I'd hate to be forced into naming it `ValidationT<T, E>` just to match `OptionT<T>` and `ResultT<T, E>`.

My only good suggestion at this point is `Optional<T>` (keeping `Some<T>` and `None`), but we could also switch to the other naming convention which is `Maybe<T>` with `Just<T>` and `Nothing` as the two variants.  I'm not as fond of the `Maybe` naming convention, but if you guys think that's better than crow-barring our way through this problem just to use a variant of the word "Option", then I could be convinced to change it.

Do you guys have any thoughts on this?
cc @brycehipp @ryanguill

**Comment by ryanguill** [comment]
I think changing it to `Optional` is fine.  I don't think we should switch to `Maybe` with the different api - there are subtle differences and I don't see any benefit in changing, especially at this point.

Why did we go with` OptionT` initially?

**Comment by iwburns** [comment]
>Why did we go with `OptionT` initially?

I wanted this library to be something that could be used in the browser as well as other contexts, but sadly `Option` is already a global in the browser.  This doesn't _completely_ prohibit us from using `Option`, but since most of the time you'd want to import `Option`/`Result` directly (so you could write `Option.some(1)`) instead of just importing `nullshield` as a whole (and having to write `nullshield.Option.some(1)`) it'd be pretty annoying to be forced into the latter in the browser.

I couldn't think of a good way around this at the time, so I just stuck a `T` on the end of the name and went with it.  Thinking back now `Optional` is a much better option that I either simply didn't think of or rejected for some unknown reason.

However, if you can think of a better solution to this problem, I'm all ears.

**Comment by iwburns** [comment]
So, summing up here, just to be clear about the result (heh) of making this change:

|Before|After|
|---|---|
|`OptionT<T>`|`Optional<T>`|
|`ResultT<T, E>`|`Result<T, E>`|
|`ValidationT<T, E>`*|`Validation<T, E>`*|

\*(assuming we decide to build this one)

Seem good to you guys?

I'm slightly annoyed by the fact that `Optional` is now an adjective and they both used to be nouns.  I would have liked for it to all be symmetrical in that aspect, but I guess it's not a big deal.

**Comment by ryanguill** [comment]
LGTM.  Think of them as containers and all of them are adjectives.  Optional Container, Result Container, Validation Container.

**Comment by brycehipp** [comment]
In total agreement of the name change.

Thinking of them as containers definitely helps wrap my mind around them too.

**Comment by iwburns** [comment]
Awesome! I'll get to work on this asap. Thanks for the feedback here guys!
